<a href="https://colab.research.google.com/github/dhoneshruti59-cloud/task25/blob/main/task25_3ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [2]:
from google.colab import files
uploaded=files.upload()

Saving Iris.csv to Iris.csv

In [4]:
df=pd.read_csv("/content/Iris.csv")

In [5]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
X=df.drop('species',axis=1)
y=df['species']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
model=SVC()
model.fit(X_train, y_train)

SVC()

In [12]:
param_grid = {
    'C': [1, 10, 20],
    'kernel': ['linear', 'rbf']
}

In [13]:
grid = GridSearchCV(model, param_grid, cv=5)
grid.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20], 'kernel': ['linear', 'rbf']})

In [14]:
results = pd.DataFrame(grid.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001825,0.000460,0.001339,0.000308,1,linear,"{'C': 1, 'kernel': 'linear'}",1.000000,0.958333,0.875000,1.000000,0.958333,0.958333,0.045644,1
1,0.001589,0.000089,0.001161,0.000024,1,rbf,"{'C': 1, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,0.958333,0.950000,0.061237,3
2,0.001523,0.000056,0.001123,0.000007,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,0.958333,0.833333,0.958333,1.000000,0.950000,0.061237,3
3,0.001490,0.000030,0.001134,0.000017,10,rbf,"{'C': 10, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,0.958333,0.950000,0.061237,3
4,0.001524,0.000038,0.001154,0.000046,20,linear,"{'C': 20, 'kernel': 'linear'}",0.958333,0.958333,0.833333,1.000000,1.000000,0.950000,0.061237,3
5,0.001464,0.000023,0.001126,0.000019,20,rbf,"{'C': 20, 'kernel': 'rbf'}",1.000000,0.958333,0.833333,1.000000,1.000000,0.958333,0.064550,1

In [15]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.958333
1        1          rbf         0.950000
2       10       linear         0.950000
3       10          rbf         0.950000
4       20       linear         0.950000
5       20          rbf         0.958333

In [16]:
print("Best Parameters :", grid.best_params_)

Best Parameters : {'C': 1, 'kernel': 'linear'}

In [17]:
print("Best Score :", grid.best_score_)

Best Score : 0.9583333333333334